let isJsHard = false;
let isJsEasy = true;
console.log(isJsHard, isJsEasy);
let isJsFun = true;
let isJsBoring = false;
console.log(isJsFun, isJsBoring);
let isJsInteresting = true;
let isJsUninteresting = false;
console.log(isJsInteresting, isJsUninteresting);
let isJsCool = true;
let isJsUncool = false;
console.log(isJsCool, isJsUncool);
let isJsAwesome = true;
let isJsUnawesome = false;
console.log(isJsAwesome, isJsUnawesome);
let isJsGood = true;
let isJsBad = false;
console.log(isJsGood, isJsBad);
let isJsBest = true;
let isJsWorst = false;
console.log(isJsBest, isJsWorst);
let isJsBetter = true;
let isJsWorse = false;
console.log(isJsBetter, isJsWorse);
let isJsGreat = true;
let isJsNotGreat = false;
console.log(isJsGreat, isJsNotGreat);
let isJsExcellent = true;
let isJsNotExcellent = false;
console.log(isJsExcellent, isJsNotExcellent);
let isJsPerfect = true;
let isJsNotPerfect = false;
console.log(isJsPerfect, isJsNotPerfect);
